'use client';

import { Suspense, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { addDoc, collection, doc, getDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../../config/firebase';

type SellRequest = { id: string; deviceType?: string; deviceName?: string; brand?: string; condition?: string; expectedPrice?: number; finalAmount?: number; status?: string; paymentMethod?: string; };
function TrackOrderContent() {
  const searchParams = useSearchParams(); const [id, setId] = useState(() => searchParams.get('order') ?? ''); const [request, setRequest] = useState<SellRequest | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [rating, setRating] = useState(0); const [rated, setRated] = useState(false);
  const track = async (event: React.FormEvent) => { event.preventDefault(); if (!id.trim()) return; setLoading(true); setError(''); setRequest(null); try { const snapshot = await getDoc(doc(db, 'sellRequests', id.trim())); if (snapshot.exists()) setRequest({ id: snapshot.id, ...snapshot.data() } as SellRequest); else setError("We couldn't find that sell request. Check the ID and try again."); } catch (issue) { console.error(issue); setError('Something went wrong while loading your request.'); } finally { setLoading(false); } };
  const submitRating = async () => { if (!request || !rating) return; try { await addDoc(collection(db, 'reviews'), { requestId: request.id, rating, type: 'sell', createdAt: serverTimestamp() }); setRated(true); } catch { setError('We could not save your rating.'); } };
  const label = request?.status === 'rejected' ? 'Not approved' : request?.status === 'completed' ? 'Completed & paid' : request?.status === 'payment_completed' ? 'Payment completed' : request?.status === 'inspected' ? 'Inspection completed' : request?.status === 'pickup_scheduled' ? 'Pickup scheduled' : 'Pickup request received';
  return <div className="tracking-page"><section><span className="eyebrow"><i /> Sell request tracker</span><h1>See where your device <em>is in the process.</em></h1><p>Enter the unique request ID shown after you submitted your device.</p><form onSubmit={track}><input value={id} onChange={(event) => setId(event.target.value)} placeholder="Paste your request ID" /><button className="btn-primary" disabled={loading}>{loading ? 'Searching…' : 'Track request'}</button></form>{error && <div className="track-error">{error}</div>}{request && <article className="track-card"><div><span>REQUEST STATUS</span><b className={`track-status ${request.status || 'pending'}`}>{label}</b></div><h2>{request.brand || 'Device'} {request.deviceName || ''}</h2><p>{request.deviceType || 'Device'} · {request.condition || 'Condition not supplied'}</p><dl><div><dt>Expected value</dt><dd>₹{Number(request.expectedPrice || 0).toLocaleString('en-IN')}</dd></div>{request.finalAmount ? <div><dt>Final paid amount</dt><dd>₹{Number(request.finalAmount).toLocaleString('en-IN')} · {request.paymentMethod || 'Payment'}</dd></div> : null}<div><dt>Tracking ID</dt><dd>{request.id}</dd></div></dl>{['completed', 'payment_completed'].includes(request.status || '') && <div style={{ marginTop: 20 }}><b>{rated ? 'Thanks for rating Selltronics!' : 'How was your experience?'}</b>{!rated && <div style={{ display: 'flex', gap: 8, marginTop: 10 }}>{[1, 2, 3, 4, 5].map((star) => <button type="button" key={star} onClick={() => setRating(star)} aria-label={`${star} stars`} style={{ border: 0, background: 'transparent', fontSize: 24, cursor: 'pointer', color: star <= rating ? '#f59e0b' : '#c7bfd9' }}>★</button>)}<button className="btn-ghost" type="button" disabled={!rating} onClick={submitRating}>Submit</button></div>}</div>}<small>We&apos;ll update this record as pickup, inspection, payment, and completion progress.</small></article>}</section></div>;
}
export default function TrackOrderPage() { return <Suspense fallback={<div className="admin-loading">Loading tracker…</div>}><TrackOrderContent /></Suspense>; }
