'use client';

import { useState } from 'react';
import { doc, updateDoc } from 'firebase/firestore';
import { db } from '@/firebase';

type Order = { id: string; customerName?: string; userName?: string; deviceName?: string; deviceType?: string; price?: number; totalPrice?: number; status?: string; createdAt?: { toDate?: () => Date } | string; };
const options = ['Pending Delivery', 'Out for Delivery', 'Delivered', 'Cancelled'];
export default function AdminOrdersTable({ orders }: { orders: Order[] }) {
  const [editing, setEditing] = useState<string | null>(null); const [status, setStatus] = useState(''); const [saving, setSaving] = useState(false);
  const save = async () => { if (!editing) return; setSaving(true); try { await updateDoc(doc(db, 'orders', editing), { status, deliveredAt: status === 'Delivered' ? new Date() : null, updatedAt: new Date() }); window.location.reload(); } catch (error) { console.error('Could not update order', error); } finally { setSaving(false); } };
  return <><div style={{ overflowX: 'auto' }}><table className="data-table"><thead><tr><th>Order ID</th><th>Customer</th><th>Device</th><th>COD amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{orders.length === 0 ? <tr><td colSpan={6} style={{ textAlign: 'center', padding: 40 }}>No orders found</td></tr> : orders.map((order) => <tr key={order.id}><td style={{ fontWeight: 600 }}>#{order.id.slice(0, 6)}</td><td>{order.customerName || order.userName || 'N/A'}</td><td>{order.deviceName || order.deviceType || 'N/A'}</td><td style={{ fontWeight: 600, color: 'var(--violet-700)' }}>₹{Number(order.price || order.totalPrice || 0).toLocaleString('en-IN')}</td><td><span className={`badge ${order.status === 'Delivered' ? 'success' : order.status === 'Cancelled' ? 'danger' : 'pending'}`}>{order.status || 'Pending Delivery'}</span></td><td><button className="btn-ghost" type="button" onClick={() => { setEditing(order.id); setStatus(order.status || 'Pending Delivery'); }}>Update</button></td></tr>)}</tbody></table></div>{editing && <div className="overlay open"><div className="modal"><button className="modal-close" onClick={() => setEditing(null)}>×</button><h3>Update delivery</h3><p>Confirm the delivery-person update after cash/UPI payment is collected.</p><label className="field"><span>Order status</span><select value={status} onChange={(e) => setStatus(e.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select></label><button className="btn-primary" disabled={saving} onClick={save}>{saving ? 'Saving…' : 'Save customer status'}</button></div></div>}</>;
}
